$repo='C:\Users\adich\OneDrive\Documents\Repos\agent-civ-lab'
$dest='C:\Users\adich\OneDrive\Documents\AI-Vault\700 Research\Agent Civilizations\Context Review\Final Registry'
$reg=Join-Path $repo 'docs/research/context_review/registry'
$ver=Join-Path $repo 'docs/research/context_review/verification'
function Value($o,$names) {foreach($n in $names){if($o.$n){return [string]$o.$n}};return 'unknown'}
function Hash($t){$sha=[System.Security.Cryptography.SHA256]::Create();return ([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($t))).Replace('-','').ToLower()).Substring(0,20)}
$sources=Import-Csv (Join-Path $reg 'sources.csv')
$normalized=foreach($s in $sources){
$r=$s.record_json|ConvertFrom-Json
$work='candidate:url:'+ (Hash $s.primary_url);$version='unknown';$aliases=$s.primary_url;$identity='URL candidate; publication aliases unresolved'
if($s.primary_url -match 'arxiv.org/(?:html|abs|pdf)/(\d{4}\.\d{4,5})(v\d+)?'){$work='arxiv:'+$Matches[1];if($Matches[2]){$version=$work+$Matches[2]}else{$version='unknown (unversioned arXiv URL)'};$aliases=$s.primary_url+';'+$work;$identity='arXiv work candidate; retained pinned version when explicit'}
$doi=Value $r @('doi','identifier');if($doi -match '^10\.\d{4,9}/'){$work='doi:'+$doi.ToLower();$aliases+=';'+$work;$identity='DOI supplied in original metadata; mirror identity not byte-verified'}
if($s.primary_url -match 'doi.org/(10\..+)'){$work='doi:'+$Matches[1].ToLower();$aliases+=';'+$work;$identity='DOI from URL; publication edition unresolved'}
$pin=Value $r @('pinned_version','version');if($version -like 'arxiv:*'){$pin=$version};if($pin -eq 'unknown' -and $version -eq 'unknown'){$pin='unknown (original artifact URL retained)'}
$stage='unknown';if($s.reading_status -match 'unavailable'){$stage='unavailable'}elseif($s.reading_status -match 'partial access'){$stage='access partial; reading scope unknown'}elseif($s.reading_status -match 'abstract'){$stage='abstract-only'}elseif($s.reading_status -match 'screen|search|discovered'){$stage='metadata-only'}elseif($s.reading_status -eq 'full-text read'){$stage='complete full-text read (author assertion only)'}elseif($s.reading_status -match 'full|key_claim_verified'){$stage='selected full-text passages (conservative; author assertion only)'}
$lineage='unknown (authors/data/models/tasks independence not audited)';if($s.registry_id -in @('R2:S7','R9:R9-S07')){$identity='confirmed duplicate document lanes: arxiv:2406.12045v1';$lineage='same tau-bench work/version; retain separate lane records'}
if($s.registry_id -in @('R4:S4','R4:S8')){$lineage='potential Ostrom lecture/published adaptation lineage; not merged';$identity='separate URL candidates pending exact edition/text collation'}
$events='none assigned at source-record level; claim checks separate';if($s.registry_id -eq 'R9:R9-S02'){$events='Independent/extra:R9-C02 unresolved access; Executive_C/E12 successful access; published pp384–385; calibration unresolved'}
[pscustomobject][ordered]@{review_record_id=$s.registry_id;work_id=$work;work_identity_status=$identity;version_id=$version;pinned_version=$pin;artifact_id='url:'+ (Hash $s.primary_url);artifact_url=$s.primary_url;artifact_hash='unknown (no retrieved artifact hash)';aliases=$aliases;title=$s.title;authors=Value $r @('authors');year=Value $r @('year');publication_status=Value $r @('publication_status');retrieval_date=Value $r @('retrieval_date');author_reading_stage=$stage;original_author_reading_label=$s.reading_status;author_locators=Value $r @('locators','exact_locators','locator');independent_verification='not inferred from author label; see claims_status.csv';independent_verification_events=$events;reviewer_independence='unknown (no prior-exposure audit)';evidence_lineage=$lineage;original_independent_verification=$s.independent_verification;provenance='repo docs/research/context_review/registry/sources.csv#'+$s.registry_id;record_json=$s.record_json}
}
$normalized|Export-Csv (Join-Path $dest 'sources_normalized.csv') -NoTypeInformation -Encoding utf8
$checks=Import-Csv (Join-Path $ver 'Independent/checks.csv')
$manifest=Get-Content (Join-Path $ver 'Independent/sample_manifest.json') -Raw|ConvertFrom-Json
$claims=Import-Csv (Join-Path $reg 'claims.csv')
$rows=@(foreach($c in $claims){$r=$c.record_json|ConvertFrom-Json;$check=$checks|Where-Object check_id -eq $c.registry_id;$sample=$manifest.rows|Where-Object registry_id -eq $c.registry_id;$link=Value $r @('source_id','source_ids','sources');if($link -ne 'unknown'){$link=$c.stream+':'+$link};[pscustomobject][ordered]@{row_type='original claim';row_id=$c.registry_id;original_claim_id=Value $r @('claim_id');source_review_record_links=$link;sample_index=if($sample){[string]$sample.index}else{'not sampled'};status=if($check){$check.category}else{'not independently checked by this sample'};allowed_wording=if($check){$check.passage_paraphrase}else{'no verification-based promotion; original wording retained in record_json'};limits=if($check){$check.scope}else{'91-row inventory is not fully verified'};exact_locator=if($check){$check.locator}else{Value $r @('exact_locator','locator')};check_file=if($check){'verification/Independent/checks.csv; checks.md'}else{'none assigned'};event_id=if($check){'Independent/'+$check.check_id}else{'none'};provenance='registry/claims.csv#'+$c.registry_id;record_json=$c.record_json}})
foreach($c in $checks|Where-Object check_id -like 'extra:*'){$rows+=[pscustomobject][ordered]@{row_type='additional independent event';row_id=$c.check_id;original_claim_id='unknown (no exact registry-row mapping asserted)';source_review_record_links='unknown';sample_index='targeted, not random sample';status=$c.category;allowed_wording=$c.passage_paraphrase;limits=$c.scope;exact_locator=$c.locator;check_file='verification/Independent/checks.csv; checks.md';event_id='Independent/'+$c.check_id;provenance='verification/Independent/checks.csv';record_json='unknown (event is not original claim row)'}}
foreach($lane in @('Executive_A','Executive_B','Executive_C')){foreach($c in (Import-Csv (Join-Path $ver ($lane+'/checks.csv')))){$wording=Value $c @('permitted_final_wording','allowed_scope');$rows+=[pscustomobject][ordered]@{row_type=if($c.claim_id -match '^E\d{2}$'){'executive check'}else{'supplemental correction'};row_id=$c.claim_id;original_claim_id='not an original registry row';source_review_record_links='see exact version/locator and check file; no automatic claim-row promotion';sample_index='targeted executive verification';status=$c.status;allowed_wording=$wording;limits=Value $c @('critical_limit','limits','independent_check_provenance');exact_locator=Value $c @('source_version_and_locator','exact_locator','source_version_passages');check_file='verification/'+$lane+'/checks.csv; checks.md; allowed_final_wording.md';event_id=$lane+'/'+$c.claim_id;provenance='verification/'+$lane+'/checks.csv';record_json=($c|ConvertTo-Json -Compress)}}}
$rows|Export-Csv (Join-Path $dest 'claims_status.csv') -NoTypeInformation -Encoding utf8
[pscustomobject]@{sources=$normalized.Count;original_claims=$claims.Count;claim_and_event_rows=$rows.Count;sample_rows=$manifest.rows.Count;search_entries=(Import-Csv (Join-Path $reg 'search_log.csv')).Count}|ConvertTo-Json
